id: automergeTriggers
name: GitOps.PullRequestIssueManagement
description: Handles enabling / disabling automerge
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Enable Auto Merge when the "auto-merge" label is present
      if:
      - payloadType: Pull_Request
      - hasLabel:
          label: auto-merge
      then:
      - enableAutoMerge:
          mergeMethod: Squash
    - description: Disable Auto Merge when the "auto-merge" label is not present
      if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: auto-merge
      then:
      - disableAutoMerge
onFailure:
onSuccess: