id: prAutoApproval.formatter
name: GitOps.PullRequestIssueManagement
description: Automatically approves formatting PRs cut by automation
owner:
resource: repository
disabled: False
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Create PRs when code formatting is run
      if:
        - payloadType: Issues
        - isAction:
            action: Opened
        - bodyContains:
            pattern: chores/format/main
            isRegex: False
        - hasLabel:
            label: 'code-formatting-automation'
        - isActivitySender:
            user: github-actions[bot]
            issueAuthor: True
      then:
        - createPullRequest:
            head: chores/format/main
            base: main
            title: "Reformat code"
            body: "Update code to match the house style 😎"
            labels: 'code-formatting-automation'
        - closeIssue
    - description: Approve PRs submitted by microsoft-github-policy-service with the "code-formatting-automation" label
      triggerOnOwnActions: True
      if:
      - payloadType: Pull_Request
      - hasLabel:
          label: 'code-formatting-automation'
      - not:
          hasLabel:
            label: auto-merge
      - isActivitySender:
          user: microsoft-github-policy-service[bot]
      then:
      - approvePullRequest:
          comment: ':shipit:'
      - addLabel:
          label: auto-merge
      - enableAutoMerge:
          mergeMethod: Squash
onFailure:
onSuccess:
