id: prMgmt.dependabot
name: GitOps.PullRequestIssueManagement
description: Approves and merges Dependabot PRs
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Approve PRs submitted by dependabot with the "dependencies" label
        if:
          - payloadType: Pull_Request
          - hasLabel:
              label: dependencies
          - not:
              hasLabel:
                label: auto-merge
          - isActivitySender:
              user: dependabot[bot]
              issueAuthor: False
        then:
          - approvePullRequest:
              comment: ":shipit:"
          - addLabel:
              label: auto-merge
          - enableAutoMerge:
              mergeMethod: Squash
onFailure:
onSuccess:
