id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: "Close issues with 'Status: No Recent Activity'"
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: awaiting response
      - hasLabel:
          label: 'Status: No Recent Activity'
      - noActivitySince:
          days: 10
      actions:
      - closeIssue
    - description: "Add 'Status: No Recent Activity' label to issues"
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: awaiting response
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: 'Status: No Recent Activity'
      actions:
      - addLabel:
          label: 'Status: No Recent Activity'
      - addReply:
          reply: 'Hi ${issueAuthor}, this issue has been marked as stale because it was labeled as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. Thanks for contributing to bicep! :smile: :mechanical_arm:'
    eventResponderTasks:
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: awaiting response
      - isOpen
      then:
      - addLabel:
          label: 'Needs: Attention :wave:'
      - removeLabel:
          label: awaiting response
      description: "Replace 'Needs: Author Feedback' with 'Needs: Attention' label when author comments"
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      - addLabel:
          label: 'Needs: Triage :mag:'
      description: "[Closed Issues] Remove 'Status: No Recent Activity' label from issues and add Needs: Triage"
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      description: "Remove 'Status: No Recent Activity' label when an issue is commented on"
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      then:
      - addCodeFlowLink
      description: "Adds a link to a pull request body that allows Microsoft reviewers to open the pull request in CodeFlow"
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: dependencies
      - not:
          hasLabel:
            label: auto-merge
      - isActivitySender:
          user: dependabot[bot]
          issueAuthor: False
      then:
      - approvePullRequest:
          comment: ':shipit:'
      - addLabel:
          label: auto-merge
      description: "Approve and apply 'auto-merge' label to dependabot PRs"
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: auto-merge
      then:
      - enableAutoMerge:
          mergeMethod: Squash
      description: "Auto merge PRs"
    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: auto-merge
      then:
      - disableAutoMerge
      description: "Disable PR auto merge"
onFailure: 
onSuccess: 
