codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        flags:
          - dotnet
        paths:
          - src

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no