<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bicep.Core\Bicep.Core.csproj" />
    <ProjectReference Include="..\Bicep.Decompiler\Bicep.Decompiler.csproj" />
    <ProjectReference Include="..\Bicep.Testing\Bicep.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Nerdbank.GitVersioning" />
  </ItemGroup>
</Project>
