var textLoadDirectory = loadTextContent('Assets/path/to/nothing')
//@[4:21) Variable textLoadDirectory. Type: string. Declaration start char: 0, length: 65
var binaryLoadDirectory = loadFileAsBase64('Assets/path/to/nothing')
//@[4:23) Variable binaryLoadDirectory. Type: string. Declaration start char: 0, length: 68

var textLoadFileMissing = loadTextContent('Assets/nothing.file')
//@[4:23) Variable textLoadFileMissing. Type: string. Declaration start char: 0, length: 64
var binaryLoadFileMissing = loadFileAsBase64('Assets/nothing.file')
//@[4:25) Variable binaryLoadFileMissing. Type: string. Declaration start char: 0, length: 67

var textLoadFilePathEmpty = loadTextContent('')
//@[4:25) Variable textLoadFilePathEmpty. Type: string. Declaration start char: 0, length: 47
var binaryLoadFilePathEmpty = loadFileAsBase64('')
//@[4:27) Variable binaryLoadFilePathEmpty. Type: string. Declaration start char: 0, length: 50

var textLoadInvalidCharactersPath1 = loadTextContent('Assets\\TextFile.txt')
//@[4:34) Variable textLoadInvalidCharactersPath1. Type: string. Declaration start char: 0, length: 76
var binaryLoadInvalidCharactersPath1 = loadFileAsBase64('Assets\\binary')
//@[4:36) Variable binaryLoadInvalidCharactersPath1. Type: string. Declaration start char: 0, length: 73

var textLoadInvalidCharactersPath2 = loadTextContent('/Assets/TextFile.txt')
//@[4:34) Variable textLoadInvalidCharactersPath2. Type: string. Declaration start char: 0, length: 76
var binaryLoadInvalidCharactersPath2 = loadFileAsBase64('/Assets/binary')
//@[4:36) Variable binaryLoadInvalidCharactersPath2. Type: string. Declaration start char: 0, length: 73

var textLoadInvalidCharactersPath3 = loadTextContent('file://Assets/TextFile.txt')
//@[4:34) Variable textLoadInvalidCharactersPath3. Type: string. Declaration start char: 0, length: 82
var binaryLoadInvalidCharactersPath3 = loadFileAsBase64('file://Assets/binary')
//@[4:36) Variable binaryLoadInvalidCharactersPath3. Type: string. Declaration start char: 0, length: 79


var textLoadUnsupportedEncoding = loadTextContent('Assets/TextFile.txt', 'windows-1250')
//@[4:31) Variable textLoadUnsupportedEncoding. Type: error. Declaration start char: 0, length: 88

var textLoadWrongEncoding01 = loadTextContent('Assets/encoding-iso.txt', 'us-ascii')
//@[4:27) Variable textLoadWrongEncoding01. Type: '?\t\tinverted exclamation mark\n?\t\tcent\n?\t\tpound\n?\t\tcurrency\n?\t\tyen\n?\t\tbroken vertical bar\n?\t\tsection\n?\t\tspacing diaeresis\n?\t\tcopyright\n?\t\tfeminine ordinal indicator\n?\t\tangle quotation mark (left)\n?\t\tnegation\n?\t\tsoft hyphen\n?\t\tregistered trademark\n?\t\tspacing macron\n?\t\tdegree\n?\t\tplus-or-minus\n?\t\tsuperscript 2\n?\t\tsuperscript 3\n?\t\tspacing acute\n?\t\tparagraph\n?\t\tmiddle dot\n?\t\tspacing cedilla\n?\t\tsuperscript 1\n?\t\tmasculine ordinal indicator\n?\t\tangle quotation mark (right)\n?\t\tfraction 1/4\n?\t\tfraction 1/2\n?\t\tfraction 3/4\n?\t\tinverted question mark\n?\t\tcapital a, grave accent\n?\t\tcapital a, acute accent\n?\t\tcapital a, circumflex accent\n?\t\tcapital a, tilde\n?\t\tcapital a, umlaut mark\n?\t\tcapital a, ring\n?\t\tcapital ae\n?\t\tcapital c, cedilla\n?\t\tcapital e, grave accent\n?\t\tcapital e, acute accent\n?\t\tcapital e, circumflex accent\n?\t\tcapital e, umlaut mark\n?\t\tcapital i, grave accent\n?\t\tcapital i, acute accent\n?\t\tcapital i, circumflex accent\n?\t\tcapital i, umlaut mark\n?\t\tcapital eth, Icelandic\n?\t\tcapital n, tilde\n?\t\tcapital o, grave accent\n?\t\tcapital o, acute accent\n?\t\tcapital o, circumflex accent\n?\t\tcapital o, tilde\n?\t\tcapital o, umlaut mark\n?\t\tmultiplication\n?\t\tcapital o, slash\n?\t\tcapital u, grave accent\n?\t\tcapital u, acute accent\n?\t\tcapital u, circumflex accent\n?\t\tcapital u, umlaut mark\n?\t\tcapital y, acute accent\n?\t\tcapital THORN, Icelandic\n?\t\tsmall sharp s, German\n?\t\tsmall a, grave accent\n?\t\tsmall a, acute accent\n?\t\tsmall a, circumflex accent\n?\t\tsmall a, tilde\n?\t\tsmall a, umlaut mark\n?\t\tsmall a, ring\n?\t\tsmall ae\n?\t\tsmall c, cedilla\n?\t\tsmall e, grave accent\n?\t\tsmall e, acute accent\n?\t\tsmall e, circumflex accent\n?\t\tsmall e, umlaut mark\n?\t\tsmall i, grave accent\n?\t\tsmall i, acute accent\n?\t\tsmall i, circumflex accent\n?\t\tsmall i, umlaut mark\n?\t\tsmall eth, Icelandic\n?\t\tsmall n, tilde\n?\t\tsmall o, grave accent\n?\t\tsmall o, acute accent\n?\t\tsmall o, circumflex accent\n?\t\tsmall o, tilde\n?\t\tsmall o, umlaut mark\n?\t\tdivision\n?\t\tsmall o, slash\n?\t\tsmall u, grave accent\n?\t\tsmall u, acute accent\n?\t\tsmall u, circumflex accent\n?\t\tsmall u, umlaut mark\n?\t\tsmall y, acute accent\n?\t\tsmall thorn, Icelandic\n?\t\tsmall y, umlaut mark\n'. Declaration start char: 0, length: 84
var textLoadWrongEncoding02 = loadTextContent('Assets/encoding-iso.txt', 'utf-8')
//@[4:27) Variable textLoadWrongEncoding02. Type: '�\t\tinverted exclamation mark\n�\t\tcent\n�\t\tpound\n�\t\tcurrency\n�\t\tyen\n�\t\tbroken vertical bar\n�\t\tsection\n�\t\tspacing diaeresis\n�\t\tcopyright\n�\t\tfeminine ordinal indicator\n�\t\tangle quotation mark (left)\n�\t\tnegation\n�\t\tsoft hyphen\n�\t\tregistered trademark\n�\t\tspacing macron\n�\t\tdegree\n�\t\tplus-or-minus\n�\t\tsuperscript 2\n�\t\tsuperscript 3\n�\t\tspacing acute\n�\t\tparagraph\n�\t\tmiddle dot\n�\t\tspacing cedilla\n�\t\tsuperscript 1\n�\t\tmasculine ordinal indicator\n�\t\tangle quotation mark (right)\n�\t\tfraction 1/4\n�\t\tfraction 1/2\n�\t\tfraction 3/4\n�\t\tinverted question mark\n�\t\tcapital a, grave accent\n�\t\tcapital a, acute accent\n�\t\tcapital a, circumflex accent\n�\t\tcapital a, tilde\n�\t\tcapital a, umlaut mark\n�\t\tcapital a, ring\n�\t\tcapital ae\n�\t\tcapital c, cedilla\n�\t\tcapital e, grave accent\n�\t\tcapital e, acute accent\n�\t\tcapital e, circumflex accent\n�\t\tcapital e, umlaut mark\n�\t\tcapital i, grave accent\n�\t\tcapital i, acute accent\n�\t\tcapital i, circumflex accent\n�\t\tcapital i, umlaut mark\n�\t\tcapital eth, Icelandic\n�\t\tcapital n, tilde\n�\t\tcapital o, grave accent\n�\t\tcapital o, acute accent\n�\t\tcapital o, circumflex accent\n�\t\tcapital o, tilde\n�\t\tcapital o, umlaut mark\n�\t\tmultiplication\n�\t\tcapital o, slash\n�\t\tcapital u, grave accent\n�\t\tcapital u, acute accent\n�\t\tcapital u, circumflex accent\n�\t\tcapital u, umlaut mark\n�\t\tcapital y, acute accent\n�\t\tcapital THORN, Icelandic\n�\t\tsmall sharp s, German\n�\t\tsmall a, grave accent\n�\t\tsmall a, acute accent\n�\t\tsmall a, circumflex accent\n�\t\tsmall a, tilde\n�\t\tsmall a, umlaut mark\n�\t\tsmall a, ring\n�\t\tsmall ae\n�\t\tsmall c, cedilla\n�\t\tsmall e, grave accent\n�\t\tsmall e, acute accent\n�\t\tsmall e, circumflex accent\n�\t\tsmall e, umlaut mark\n�\t\tsmall i, grave accent\n�\t\tsmall i, acute accent\n�\t\tsmall i, circumflex accent\n�\t\tsmall i, umlaut mark\n�\t\tsmall eth, Icelandic\n�\t\tsmall n, tilde\n�\t\tsmall o, grave accent\n�\t\tsmall o, acute accent\n�\t\tsmall o, circumflex accent\n�\t\tsmall o, tilde\n�\t\tsmall o, umlaut mark\n�\t\tdivision\n�\t\tsmall o, slash\n�\t\tsmall u, grave accent\n�\t\tsmall u, acute accent\n�\t\tsmall u, circumflex accent\n�\t\tsmall u, umlaut mark\n�\t\tsmall y, acute accent\n�\t\tsmall thorn, Icelandic\n�\t\tsmall y, umlaut mark\n'. Declaration start char: 0, length: 81
var textLoadWrongEncoding03 = loadTextContent('Assets/encoding-iso.txt', 'utf-16BE')
//@[4:27) Variable textLoadWrongEncoding03. Type: 'ꄉ३湶敲瑥搠數捬慭慴楯渠浡牫ઢउ捥湴ણउ灯畮搊ꐉॣ畲牥湣礊ꔉॹ敮દउ扲潫敮⁶敲瑩捡氠扡爊꜉ॳ散瑩潮નउ獰慣楮朠摩慥牥獩猊꤉ॣ潰祲楧桴પउ晥浩湩湥⁯牤楮慬⁩湤楣慴潲ફउ慮杬攠煵潴慴楯渠浡牫 汥晴⤊갉८敧慴楯渊괉ॳ潦琠桹灨敮મउ牥杩獴敲敤⁴牡摥浡牫યउ獰慣楮朠浡捲潮રउ摥杲敥઱उ灬畳ⵯ爭浩湵猊눉ॳ異敲獣物灴′ળउ獵灥牳捲楰琠㌊됉ॳ灡捩湧⁡捵瑥શउ灡牡杲慰栊뜉७楤摬攠摯琊렉ॳ灡捩湧⁣敤楬污હउ獵灥牳捲楰琠ㄊ먉७慳捵汩湥⁯牤楮慬⁩湤楣慴潲઻उ慮杬攠煵潴慴楯渠浡牫 物杨琩઼उ晲慣瑩潮‱⼴ઽउ晲慣瑩潮‱⼲ાउ晲慣瑩潮″⼴િउ楮癥牴敤ⁱ略獴楯渠浡牫ીउ捡灩瑡氠愬⁧牡癥⁡捣敮琊섉ॣ慰楴慬⁡Ⱐ慣畴攠慣捥湴ૂउ捡灩瑡氠愬⁣楲捵浦汥砠慣捥湴ૃउ捡灩瑡氠愬⁴楬摥ૄउ捡灩瑡氠愬⁵浬慵琠浡牫ૅउ捡灩瑡氠愬⁲楮朊옉ॣ慰楴慬⁡攊윉ॣ慰楴慬⁣Ⱐ捥摩汬愊젉ॣ慰楴慬⁥Ⱐ杲慶攠慣捥湴ૉउ捡灩瑡氠攬⁡捵瑥⁡捣敮琊쨉ॣ慰楴慬⁥Ⱐ捩牣畭晬數⁡捣敮琊쬉ॣ慰楴慬⁥Ⱐ畭污畴⁭慲權찉ॣ慰楴慬⁩Ⱐ杲慶攠慣捥湴્उ捡灩瑡氠椬⁡捵瑥⁡捣敮琊츉ॣ慰楴慬⁩Ⱐ捩牣畭晬數⁡捣敮琊켉ॣ慰楴慬⁩Ⱐ畭污畴⁭慲權퀉ॣ慰楴慬⁥瑨Ⱐ䥣敬慮摩挊턉ॣ慰楴慬⁮Ⱐ瑩汤攊툉ॣ慰楴慬⁯Ⱐ杲慶攠慣捥湴૓उ捡灩瑡氠漬⁡捵瑥⁡捣敮琊퐉ॣ慰楴慬⁯Ⱐ捩牣畭晬數⁡捣敮琊픉ॣ慰楴慬⁯Ⱐ瑩汤攊혉ॣ慰楴慬⁯Ⱐ畭污畴⁭慲權휉७畬瑩灬楣慴楯渊�ॣ慰楴慬⁯Ⱐ獬慳栊�ॣ慰楴慬⁵Ⱐ杲慶攠慣捥湴૚उ捡灩瑡氠甬⁡捵瑥⁡捣敮琊�ॣ慰楴慬⁵Ⱐ捩牣畭晬數⁡捣敮琊�ॣ慰楴慬⁵Ⱐ畭污畴⁭慲權�ॣ慰楴慬⁹Ⱐ慣畴攠慣捥湴૞उ捡灩瑡氠呈佒丬⁉捥污湤楣૟उ獭慬氠獨慲瀠猬⁇敲浡渊ॳ浡汬⁡Ⱐ杲慶攠慣捥湴ૡउ獭慬氠愬⁡捵瑥⁡捣敮琊ॳ浡汬⁡Ⱐ捩牣畭晬數⁡捣敮琊ॳ浡汬⁡Ⱐ瑩汤攊ॳ浡汬⁡Ⱐ畭污畴⁭慲權ॳ浡汬⁡Ⱐ物湧૦उ獭慬氠慥૧उ獭慬氠挬⁣敤楬污૨उ獭慬氠攬⁧牡癥⁡捣敮琊ॳ浡汬⁥Ⱐ慣畴攠慣捥湴૪उ獭慬氠攬⁣楲捵浦汥砠慣捥湴૫उ獭慬氠攬⁵浬慵琠浡牫૬उ獭慬氠椬⁧牡癥⁡捣敮琊ॳ浡汬⁩Ⱐ慣畴攠慣捥湴૮उ獭慬氠椬⁣楲捵浦汥砠慣捥湴૯उ獭慬氠椬⁵浬慵琠浡牫૰उ獭慬氠整栬⁉捥污湤楣૱उ獭慬氠測⁴楬摥૲उ獭慬氠漬⁧牡癥⁡捣敮琊ॳ浡汬⁯Ⱐ慣畴攠慣捥湴૴उ獭慬氠漬⁣楲捵浦汥砠慣捥湴૵उ獭慬氠漬⁴楬摥૶उ獭慬氠漬⁵浬慵琠浡牫૷उ摩癩獩潮૸उ獭慬氠漬⁳污獨ૹउ獭慬氠甬⁧牡癥⁡捣敮琊降ॳ浡汬⁵Ⱐ慣畴攠慣捥湴ૻउ獭慬氠甬⁣楲捵浦汥砠慣捥湴ૼउ獭慬氠甬⁵浬慵琠浡牫૽उ獭慬氠礬⁡捵瑥⁡捣敮琊︉ॳ浡汬⁴桯牮Ⱐ䥣敬慮摩挊）ॳ浡汬⁹Ⱐ畭污畴⁭慲權'. Declaration start char: 0, length: 84
var textLoadWrongEncoding04 = loadTextContent('Assets/encoding-iso.txt', 'utf-16')
//@[4:27) Variable textLoadWrongEncoding04. Type: 'ড椉癮牥整⁤硥汣浡瑡潩⁮慭歲ꈊउ散瑮ꌊउ潰湵੤ত按牵敲据੹থ礉湥ꘊउ牢歯湥瘠牥楴慣⁬慢ੲধ猉捥楴湯ꠊउ灳捡湩⁧楤敡敲楳ੳ঩按灯特杩瑨ꨊउ敦業楮敮漠摲湩污椠摮捩瑡牯ꬊउ湡汧⁥畱瑯瑡潩⁮慭歲⠠敬瑦਩ব渉来瑡潩੮ভ猉景⁴票桰湥긊उ敲楧瑳牥摥琠慲敤慭歲꼊उ灳捡湩⁧慭牣湯뀊उ敤牧敥넊उ汰獵漭⵲業畮ੳল猉灵牥捳楲瑰㈠댊उ畳数獲牣灩⁴ਲ਼঴猉慰楣杮愠畣整똊उ慰慲牧灡੨ষ洉摩汤⁥潤ੴস猉慰楣杮挠摥汩慬뤊उ畳数獲牣灩⁴਱঺洉獡畣楬敮漠摲湩污椠摮捩瑡牯묊उ湡汧⁥畱瑯瑡潩⁮慭歲⠠楲桧⥴밊उ牦捡楴湯ㄠ㐯봊उ牦捡楴湯ㄠ㈯븊उ牦捡楴湯㌠㐯뼊उ湩敶瑲摥焠敵瑳潩⁮慭歲쀊उ慣楰慴⁬ⱡ朠慲敶愠捣湥ੴু按灡瑩污愠‬捡瑵⁥捡散瑮숊उ慣楰慴⁬ⱡ挠物畣晭敬⁸捡散瑮쌊उ慣楰慴⁬ⱡ琠汩敤쐊उ慣楰慴⁬ⱡ甠汭畡⁴慭歲씊उ慣楰慴⁬ⱡ爠湩੧৆按灡瑩污愠੥ে按灡瑩污挠‬散楤汬੡ৈ按灡瑩污攠‬牧癡⁥捡散瑮줊उ慣楰慴⁬ⱥ愠畣整愠捣湥ੴ৊按灡瑩污攠‬楣捲浵汦硥愠捣湥ੴো按灡瑩污攠‬浵慬瑵洠牡੫ৌ按灡瑩污椠‬牧癡⁥捡散瑮촊उ慣楰慴⁬Ⱪ愠畣整愠捣湥ੴৎ按灡瑩污椠‬楣捲浵汦硥愠捣湥ੴ৏按灡瑩污椠‬浵慬瑵洠牡੫৐按灡瑩污攠桴‬捉汥湡楤੣৑按灡瑩污渠‬楴摬੥৒按灡瑩污漠‬牧癡⁥捡散瑮팊उ慣楰慴⁬Ɐ愠畣整愠捣湥ੴ৔按灡瑩污漠‬楣捲浵汦硥愠捣湥ੴ৕按灡瑩污漠‬楴摬੥৖按灡瑩污漠‬浵慬瑵洠牡੫ৗ洉汵楴汰捩瑡潩੮৘按灡瑩污漠‬汳獡੨৙按灡瑩污甠‬牧癡⁥捡散瑮�उ慣楰慴⁬Ⱶ愠畣整愠捣湥ੴ৛按灡瑩污甠‬楣捲浵汦硥愠捣湥ੴড়按灡瑩污甠‬浵慬瑵洠牡੫ঢ়按灡瑩污礠‬捡瑵⁥捡散瑮�उ慣楰慴⁬䡔剏ⱎ䤠散慬摮捩�उ浳污⁬桳牡⁰ⱳ䜠牥慭੮ৠ猉慭汬愠‬牧癡⁥捡散瑮उ浳污⁬ⱡ愠畣整愠捣湥ੴৢ猉慭汬愠‬楣捲浵汦硥愠捣湥ੴৣ猉慭汬愠‬楴摬੥৤猉慭汬愠‬浵慬瑵洠牡੫৥猉慭汬愠‬楲杮उ浳污⁬敡उ浳污⁬Ᵽ挠摥汩慬उ浳污⁬ⱥ朠慲敶愠捣湥ੴ৩猉慭汬攠‬捡瑵⁥捡散瑮उ浳污⁬ⱥ挠物畣晭敬⁸捡散瑮उ浳污⁬ⱥ甠汭畡⁴慭歲उ浳污⁬Ⱪ朠慲敶愠捣湥ੴ৭猉慭汬椠‬捡瑵⁥捡散瑮उ浳污⁬Ⱪ挠物畣晭敬⁸捡散瑮उ浳污⁬Ⱪ甠汭畡⁴慭歲उ浳污⁬瑥ⱨ䤠散慬摮捩उ浳污⁬Ɱ琠汩敤उ浳污⁬Ɐ朠慲敶愠捣湥ੴ৳猉慭汬漠‬捡瑵⁥捡散瑮उ浳污⁬Ɐ挠物畣晭敬⁸捡散瑮उ浳污⁬Ɐ琠汩敤उ浳污⁬Ɐ甠汭畡⁴慭歲उ楤楶楳湯उ浳污⁬Ɐ猠慬桳金उ浳污⁬Ⱶ朠慲敶愠捣湥ੴ৺猉慭汬甠‬捡瑵⁥捡散瑮﬊उ浳污⁬Ⱶ挠物畣晭敬⁸捡散瑮ﰊउ浳污⁬Ⱶ甠汭畡⁴慭歲ﴊउ浳污⁬ⱹ愠畣整愠捣湥ੴ৾猉慭汬琠潨湲‬捉汥湡楤੣৿猉慭汬礠‬浵慬瑵洠牡੫'. Declaration start char: 0, length: 82
var textLoadWrongEncoding05 = loadTextContent('Assets/encoding-ascii.txt', 'iso-8859-1')
//@[4:27) Variable textLoadWrongEncoding05. Type: '32 = \n33 = !\n34 = "\n35 = #\n36 = $\n37 = %\n38 = &\n39 = \'\n40 = (\n41 = )\n42 = *\n43 = +\n44 = ,\n45 = -\n46 = .\n47 = /\n48 = 0\n49 = 1\n50 = 2\n51 = 3\n52 = 4\n53 = 5\n54 = 6\n55 = 7\n56 = 8\n57 = 9\n58 = :\n59 = ;\n60 = <\n61 = =\n62 = >\n63 = ?\n64 = @\n65 = A\n66 = B\n67 = C\n68 = D\n69 = E\n70 = F\n71 = G\n72 = H\n73 = I\n74 = J\n75 = K\n76 = L\n77 = M\n78 = N\n79 = O\n80 = P\n81 = Q\n82 = R\n83 = S\n84 = T\n85 = U\n86 = V\n87 = W\n88 = X\n89 = Y\n90 = Z\n91 = [\n92 = \\\n93 = ]\n94 = ^\n95 = _\n96 = `\n97 = a\n98 = b\n99 = c\n100 = d\n101 = e\n102 = f\n103 = g\n104 = h\n105 = i\n106 = j\n107 = k\n108 = l\n109 = m\n110 = n\n111 = o\n112 = p\n113 = q\n114 = r\n115 = s\n116 = t\n117 = u\n118 = v\n119 = w\n120 = x\n121 = y\n122 = z\n123 = {\n124 = |\n125 = }\n126 = ~'. Declaration start char: 0, length: 88
var textLoadWrongEncoding06 = loadTextContent('Assets/encoding-ascii.txt', 'utf-8')
//@[4:27) Variable textLoadWrongEncoding06. Type: '32 = \n33 = !\n34 = "\n35 = #\n36 = $\n37 = %\n38 = &\n39 = \'\n40 = (\n41 = )\n42 = *\n43 = +\n44 = ,\n45 = -\n46 = .\n47 = /\n48 = 0\n49 = 1\n50 = 2\n51 = 3\n52 = 4\n53 = 5\n54 = 6\n55 = 7\n56 = 8\n57 = 9\n58 = :\n59 = ;\n60 = <\n61 = =\n62 = >\n63 = ?\n64 = @\n65 = A\n66 = B\n67 = C\n68 = D\n69 = E\n70 = F\n71 = G\n72 = H\n73 = I\n74 = J\n75 = K\n76 = L\n77 = M\n78 = N\n79 = O\n80 = P\n81 = Q\n82 = R\n83 = S\n84 = T\n85 = U\n86 = V\n87 = W\n88 = X\n89 = Y\n90 = Z\n91 = [\n92 = \\\n93 = ]\n94 = ^\n95 = _\n96 = `\n97 = a\n98 = b\n99 = c\n100 = d\n101 = e\n102 = f\n103 = g\n104 = h\n105 = i\n106 = j\n107 = k\n108 = l\n109 = m\n110 = n\n111 = o\n112 = p\n113 = q\n114 = r\n115 = s\n116 = t\n117 = u\n118 = v\n119 = w\n120 = x\n121 = y\n122 = z\n123 = {\n124 = |\n125 = }\n126 = ~'. Declaration start char: 0, length: 83
var textLoadWrongEncoding07 = loadTextContent('Assets/encoding-ascii.txt', 'utf-16BE')
//@[4:27) Variable textLoadWrongEncoding07. Type: '㌲‽ ㌳‽‡ਲ਼㐠㴠∊㌵‽‣ਲ਼㘠㴠␊㌷‽‥ਲ਼㠠㴠☊㌹‽‧਴〠㴠⠊㐱‽ ਴㈠㴠⨊㐳‽‫਴㐠㴠Ⰺ㐵‽‭਴㘠㴠⸊㐷‽ ਴㠠㴠《㐹‽‱ਵ〠㴠㈊㔱‽″ਵ㈠㴠㐊㔳‽‵ਵ㐠㴠㘊㔵‽‷ਵ㘠㴠㠊㔷‽‹ਵ㠠㴠㨊㔹‽※ਸ਼〠㴠㰊㘱‽‽ਸ਼㈠㴠㸊㘳‽‿ਸ਼㐠㴠䀊㘵‽⁁ਸ਼㘠㴠䈊㘷‽⁃ਸ਼㠠㴠䐊㘹‽⁅਷〠㴠䘊㜱‽⁇਷㈠㴠䠊㜳‽⁉਷㐠㴠䨊㜵‽⁋਷㘠㴠䰊㜷‽⁍਷㠠㴠上㜹‽⁏ਸ〠㴠倊㠱‽⁑ਸ㈠㴠刊㠳‽⁓ਸ㐠㴠吊㠵‽⁕ਸ㘠㴠嘊㠷‽⁗ਸ㠠㴠堊㠹‽⁙ਹ〠㴠娊㤱‽⁛ਹ㈠㴠尊㤳‽⁝ਹ㐠㴠帊㤵‽ ਹ㘠㴠怊㤷‽⁡ਹ㠠㴠戊㤹‽⁣਱〰‽⁤਱〱‽⁥਱〲‽⁦਱〳‽⁧਱〴‽⁨਱〵‽⁩਱〶‽⁪਱〷‽⁫਱〸‽⁬਱〹‽⁭਱㄰‽⁮਱ㄱ‽⁯਱ㄲ‽⁰਱ㄳ‽ⁱ਱ㄴ‽⁲਱ㄵ‽⁳਱ㄶ‽⁴਱ㄷ‽⁵਱ㄸ‽⁶਱ㄹ‽⁷਱㈰‽⁸਱㈱‽⁹਱㈲‽⁺਱㈳‽⁻਱㈴‽⁼਱㈵‽⁽਱㈶‽⁾'. Declaration start char: 0, length: 86
var textLoadWrongEncoding08 = loadTextContent('Assets/encoding-ascii.txt', 'utf-16')
//@[4:27) Variable textLoadWrongEncoding08. Type: '㈳㴠ਠ㌳㴠℠㌊‴‽ਢ㔳㴠⌠㌊‶‽ਤ㜳㴠┠㌊‸‽ਦ㤳㴠✠㐊‰‽ਨㄴ㴠⤠㐊′‽ਪ㌴㴠⬠㐊‴‽ਬ㔴㴠ⴠ㐊‶‽ਮ㜴㴠⼠㐊‸‽ਰ㤴㴠ㄠ㔊‰‽ਲㄵ㴠㌠㔊′‽਴㌵㴠㔠㔊‴‽ਸ਼㔵㴠㜠㔊‶‽ਸ㜵㴠㤠㔊‸‽਺㤵㴠㬠㘊‰‽਼ㄶ㴠㴠㘊′‽ਾ㌶㴠㼠㘊‴‽ੀ㔶㴠䄠㘊‶‽ੂ㜶㴠䌠㘊‸‽੄㤶㴠䔠㜊‰‽੆ㄷ㴠䜠㜊′‽ੈ㌷㴠䤠㜊‴‽੊㔷㴠䬠㜊‶‽ੌ㜷㴠䴠㜊‸‽੎㤷㴠传㠊‰‽੐ㄸ㴠儠㠊′‽੒㌸㴠匠㠊‴‽੔㔸㴠唠㠊‶‽੖㜸㴠圠㠊‸‽੘㤸㴠夠㤊‰‽ਗ਼ㄹ㴠嬠㤊′‽ੜ㌹㴠崠㤊‴‽ਫ਼㔹㴠张㤊‶‽੠㜹㴠愠㤊‸‽੢㤹㴠挠ㄊ〰㴠搠ㄊ㄰㴠攠ㄊ㈰㴠映ㄊ㌰㴠朠ㄊ㐰㴠栠ㄊ㔰㴠椠ㄊ㘰㴠樠ㄊ㜰㴠欠ㄊ㠰㴠氠ㄊ㤰㴠洠ㄊ〱㴠渠ㄊㄱ㴠漠ㄊ㈱㴠瀠ㄊ㌱㴠焠ㄊ㐱㴠爠ㄊ㔱㴠猠ㄊ㘱㴠琠ㄊ㜱㴠甠ㄊ㠱㴠瘠ㄊ㤱㴠眠ㄊ〲㴠砠ㄊㄲ㴠礠ㄊ㈲㴠稠ㄊ㌲㴠笠ㄊ㐲㴠簠ㄊ㔲㴠素ㄊ㘲㴠縠'. Declaration start char: 0, length: 84
var textLoadWrongEncoding09 = loadTextContent('Assets/encoding-utf16.txt', 'iso-8859-1')
//@[4:27) Variable textLoadWrongEncoding09. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 88
var textLoadWrongEncoding10 = loadTextContent('Assets/encoding-utf16.txt', 'utf-8')
//@[4:27) Variable textLoadWrongEncoding10. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 83
var textLoadWrongEncoding11 = loadTextContent('Assets/encoding-utf16.txt', 'utf-16BE')
//@[4:27) Variable textLoadWrongEncoding11. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 86
var textLoadWrongEncoding12 = loadTextContent('Assets/encoding-utf16.txt', 'us-ascii')
//@[4:27) Variable textLoadWrongEncoding12. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 86
var textLoadWrongEncoding13 = loadTextContent('Assets/encoding-utf16be.txt', 'utf-16')
//@[4:27) Variable textLoadWrongEncoding13. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 86
var textLoadWrongEncoding14 = loadTextContent('Assets/encoding-utf16be.txt', 'utf-8')
//@[4:27) Variable textLoadWrongEncoding14. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 85
var textLoadWrongEncoding15 = loadTextContent('Assets/encoding-utf16be.txt', 'us-ascii')
//@[4:27) Variable textLoadWrongEncoding15. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 88
var textLoadWrongEncoding16 = loadTextContent('Assets/encoding-utf16be.txt', 'iso-8859-1')
//@[4:27) Variable textLoadWrongEncoding16. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 90
var textLoadWrongEncoding17 = loadTextContent('Assets/encoding-windows1250.txt', 'utf-16BE')
//@[4:27) Variable textLoadWrongEncoding17. Type: '婡뿳돦⁧油⁪憟'. Declaration start char: 0, length: 92
var textLoadWrongEncoding18 = loadTextContent('Assets/encoding-windows1250.txt', 'utf-16')
//@[4:27) Variable textLoadWrongEncoding18. Type: '慚朠鳪륬樠齡෱'. Declaration start char: 0, length: 90
var textLoadWrongEncoding19 = loadTextContent('Assets/encoding-windows1250.txt', 'utf-8')
//@[4:27) Variable textLoadWrongEncoding19. Type: 'Za��� g�l� ja��\r\n'. Declaration start char: 0, length: 89
var textLoadWrongEncoding20 = loadTextContent('Assets/encoding-windows1250.txt', 'us-ascii')
//@[4:27) Variable textLoadWrongEncoding20. Type: 'Za???? g??l? ja??\r\n'. Declaration start char: 0, length: 92
var textLoadWrongEncoding21 = loadTextContent('Assets/encoding-windows1250.txt', 'iso-8859-1')
//@[4:27) Variable textLoadWrongEncoding21. Type: 'Za¿ó³æ gêl¹ jañ\r\n'. Declaration start char: 0, length: 94
var textLoadWrongEncoding22 = loadTextContent('Assets/encoding-utf8.txt', 'iso-8859-1')
//@[4:27) Variable textLoadWrongEncoding22. Type: 'ðªðððâ\r\nð±âð¤\r\n\r\næè¾ç½å¸å½©äºé´\r\nåéæ±éµä¸æ¥è¿\r\nä¸¤å²¸ç¿å£°å¼ä¸ä½\r\nè½»èå·²è¿ä¸éå±±\r\n\r\nÎ  Ï Î¦ Ï\r\n\r\nð\r\n\r\nÎ±Î±\r\nÎ©Ï\r\nÎ  \r\n\r\nZaÅ¼Ã³ÅÄ gÄÅlÄ jaÅºÅ\r\n\r\nÃ¡Ã©Ã³ÃºÃ±Ã¼ - Â¡Hola!\r\n\r\näºå¤´èäºå¤´è\r\n\r\n\r\näºå¤´è\r\nÎäºå¤´èÎ±\r\n\r\nð·\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\nâ Hello\\u{20}World\\u{21} â\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\tâ\tâ\tâ\tâ\tâ\tâ\tâ\tâ\t8\r\n7\tâ\tâ\tâ\tâ\tâ\tâ\tâ\tâ\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\tâ\tâ\tâ\tâ\tâ\tâ\tâ\tâ\t2\r\n1\tâ\tâ\tâ\tâ\tâ\tâ\tâ\tâ\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 87
var textLoadWrongEncoding23 = loadTextContent('Assets/encoding-utf8.txt', 'utf-16')
//@[4:27) Variable textLoadWrongEncoding23. Type: '鿰ꪒ鿰誘鿰袘鿰閍飢ඕ邟趀鿰꒑਍਍鳦麾駧鶸뷥醺韩ප莍蟩龱駩肸韦颿਍룤뢲賧낣闥趸뷤ඏ뮽裨늷뿨螸蟩놱਍਍ꃎ켠₀ꛎ켠ආഊ颟ඎഊ츊캱න츊쾩ඉ츊ₘഠഊ娊액쎼얳쒂₇쑧얙沛藄樠액얺඄ഊ쌊쎡쎩쎳쎺쎱₼‭ꇂ潈慬ഡഊ貺ꓥ貂뫤뒤苨ඌഊഊ貺ꓥ貂਍风뫤뒤苨캌නഊ邐භ尊筵〱㌴紷਍畜䑻〸紱畜䑻㍃紷਍਍鷢₆效汬屯筵〲坽牯摬畜㉻紱膝਍਍愉戉按搉攉昉有栉ഉ㠊鲙麙鶙鮙骙鶙麙鲙㠉਍ष駢ট駢ট駢ট駢ট駢ট駢ট駢ট駢টഷ㘊उउउउ㘉਍वउउउउവ㐊उउउउ㐉਍ळउउउउള㈊香香香香香香香香㈉਍ऱ駢খ駢ঘ駢গ駢ক駢ঔ駢গ駢ঘ駢খറऊॡॢॣ।॥०१൨'. Declaration start char: 0, length: 83
var textLoadWrongEncoding24 = loadTextContent('Assets/encoding-utf8.txt', 'utf-16BE')
//@[4:27) Variable textLoadWrongEncoding24. Type: '銪颊颈趕锍૰龐뇢肍醤ഊഊ鷨뺞뷥뢝ꧤ몑됍૥趃賦놟뗤뢀ꗨ뾘ഊꓥ늸뿥ꎰ볤뢍輍૨붻鿥랲蟤뢇跥놱ഊഊ캠⃏耠캦⃏蘍਍૰龘踍਍૎뇎넍૎ꧏ褍૎頠‍਍ਗ਼懅볃독苄蜠柄駅魬쒅⁪懅뫅萍਍ૃꇃ꧃돃뫃뇃밠ⴠ슡䡯污ℍ਍૤몌듨芌賥꒴谍਍਍૤몌듨芌ഊ캘賥꒴賎넍਍૰邐뜍ੜ畻㄰㐳㝽ഊ屵筄㠰ㅽ屵筄䌳㝽ഊഊ蘠䡥汬潜畻㈰絗潲汤屵笲ㅽ⃢鶁ഊഊॡॢॣ।॥०१२ऍਸৢ馜ৢ馞ৢ馝ৢ馛ৢ馚ৢ馝ৢ馞ৢ馜सഊ㜉鼉鼉鼉鼉鼉鼉鼉鼉㜍ਸ਼उउउउशഊ㔉उउउउ㔍਴उउउउऴഊ㌉उउउउ㌍ਲৢ香ৢ香ৢ香ৢ香ৢ香ৢ香ৢ香ৢ香लഊㄉ阉頉霉锉鐉霉頉阉ㄍਉ愉戉按搉攉昉有栍'. Declaration start char: 0, length: 85
var textLoadWrongEncoding25 = loadTextContent('Assets/encoding-utf8.txt', 'us-ascii')
//@[4:27) Variable textLoadWrongEncoding25. Type: '???????????????????\r\n???????????\r\n\r\n?????????????????????\r\n?????????????????????\r\n?????????????????????\r\n?????????????????????\r\n\r\n?? ?? ?? ??\r\n\r\n????\r\n\r\n????\r\n????\r\n??  \r\n\r\nZa???????? g????l?? ja????\r\n\r\n???????????? - ??Hola!\r\n\r\n??????????????????\r\n\r\n\r\n?????????\r\n?????????????\r\n\r\n????\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n??? Hello\\u{20}World\\u{21} ???\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t???\t???\t???\t???\t???\t???\t???\t???\t8\r\n7\t???\t???\t???\t???\t???\t???\t???\t???\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t???\t???\t???\t???\t???\t???\t???\t???\t2\r\n1\t???\t???\t???\t???\t???\t???\t???\t???\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 85
var textLoadWrongEncoding26 = loadTextContent('Assets/encoding-utf8-bom.txt', 'iso-8859-1')
//@[4:27) Variable textLoadWrongEncoding26. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 91
var textLoadWrongEncoding27 = loadTextContent('Assets/encoding-utf8-bom.txt', 'utf-16')
//@[4:27) Variable textLoadWrongEncoding27. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 87
var textLoadWrongEncoding28 = loadTextContent('Assets/encoding-utf8-bom.txt', 'utf-16BE')
//@[4:27) Variable textLoadWrongEncoding28. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 89
var textLoadWrongEncoding29 = loadTextContent('Assets/encoding-utf8-bom.txt', 'us-ascii')
//@[4:27) Variable textLoadWrongEncoding29. Type: '💪😊😈🍕☕\r\n🐱‍👤\r\n\r\n朝辞白帝彩云间\r\n千里江陵一日还\r\n两岸猿声啼不住\r\n轻舟已过万重山\r\n\r\nΠ π Φ φ\r\n\r\n😎\r\n\r\nαα\r\nΩω\r\nΘ  \r\n\r\nZażółć gęślą jaźń\r\n\r\náéóúñü - ¡Hola!\r\n\r\n二头肌二头肌\r\n\r\n\r\n二头肌\r\nΘ二头肌α\r\n\r\n𐐷\r\n\\u{10437}\r\n\\u{D801}\\u{DC37}\r\n\r\n❆ Hello\\u{20}World\\u{21} ❁\r\n\r\n\ta\tb\tc\td\te\tf\tg\th\t\r\n8\t♜\t♞\t♝\t♛\t♚\t♝\t♞\t♜\t8\r\n7\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t♟\t7\r\n6\t\t\t\t\t\t\t\t\t6\r\n5\t\t\t\t\t\t\t\t\t5\r\n4\t\t\t\t\t\t\t\t\t4\r\n3\t\t\t\t\t\t\t\t\t3\r\n2\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t♙\t2\r\n1\t♖\t♘\t♗\t♕\t♔\t♗\t♘\t♖\t1\r\n\ta\tb\tc\td\te\tf\tg\th\r\n'. Declaration start char: 0, length: 89

var textOversize = loadTextContent('Assets/oversizeText.txt')
//@[4:16) Variable textOversize. Type: string. Declaration start char: 0, length: 61
var binaryOversize = loadFileAsBase64('Assets/oversizeBinary')
//@[4:18) Variable binaryOversize. Type: string. Declaration start char: 0, length: 62

var binaryAsText = loadTextContent('Assets/binary')
//@[4:16) Variable binaryAsText. Type: '���G�T���h�3q�a$�W���\t��6;�lg{[�2U�H��5�k��م\'���Rs���\\�&�h��\\�+���hN���wo\\��ð�!��f�$\n�]����g.t�-�a����8 ���1N���"!���U���&��k��$Y���E��E��W���ݗ�K�ٯ܆Mw_�p��߳�����\'��QL�Pv����O�aw��g3�������k���ėk.��S�R���%@y�"���(���-�s�(L�%]e�`��\r�]���1JD��0�u�\t��A�-�|�9yz�0ix�mؤG>���)�F�"�U�O��d�n���o<{�@�"�53��5�d�������ɶ\r2�,��}��18��nl��@�`R����*N��t�&G+5}�� �|��.P�Q(�}�߶��1ꩴN�f#�<��{��Q-�l\\�*�t�;�뤞��j�\rr�;hh2�B��ݜ,,)ŮYEhٕ��I;��L�HȊ�i3ƣw3��ӿ��7,]VT��z�9�7XR�O@�01�V�DU�m}=Z������M��D�t��Mb���M�R�t|W�0dB�*0��&�!�y����=p��h��\tJ���Ni�������ʥ����(���@$���.VYad���`�/U[7�|`;ރ��LH*���b׮ּ-Y�:�T��Q�*e�ȧ(]�nڠ�T����pW�>[|�e�9oA���&�:ʗ��cPL~G����]m��[����rO��66 @��Os�.�A}ylWBjV��x4ӈ���^iLf�r�v �?$�d�\'� �$�tP��1ßT�v.��wd\\j6�uj\rA]$��p�j�`i!�\\_��un������� :�7�s3��!���DMp�"��j9�ô�ģ��f�0B}���fZ�v�25� <hJja�7�31tHD��ԓ��>�@��I�1��K��0f;1v�;8Ҟ�b1|wq�z8��i�b����׵A9k�us�;�<@���?_iUB1D ��E�'. Declaration start char: 0, length: 51
