<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Workaround for https://github.com/microsoft/testfx/issues/4945 -->
    <!-- This is a test fixtures library, not a runnable test project -->
    <EnableMSTestRunner>false</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Samples/**/*" WithCulture="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="JsonPatch.Net" />
    <PackageReference Include="Moq" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bicep.RegistryModuleTool\Bicep.RegistryModuleTool.csproj" />
    <ProjectReference Include="..\Bicep.Testing\Bicep.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Nerdbank.GitVersioning" />
  </ItemGroup>
</Project>
