<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>Bicep</string>
    <key>scopeName</key>
    <string>source.bicep</string>
    <key>fileTypes</key>
    <array>
      <string>.bicep</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#statement</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>array-literal</key>
      <dict>
        <key>name</key>
        <string>meta.array-literal.bicep</string>
        <key>begin</key>
        <string>\[(?:\s|/\*.*\*/)*(?!\bfor\b)</string>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#array-property</string>
          </dict>
        </array>
      </dict>
      <key>array-property</key>
      <dict>
        <key>name</key>
        <string>meta.array-property.bicep</string>
        <key>begin</key>
        <string>^(?!(?:\s|/\*.*\*/)*])</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>block-comment</key>
      <dict>
        <key>name</key>
        <string>comment.block.bicep</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#line-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-comment</string>
          </dict>
        </array>
      </dict>
      <key>decorator</key>
      <dict>
        <key>name</key>
        <string>meta.decorator.bicep</string>
        <key>begin</key>
        <string>@</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>escape-character</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.bicep</string>
        <key>match</key>
        <string>\\(u[0-9A-Fa-f]{6}|n|r|t|\\|'|\${)</string>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#for-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-verbatim</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#named-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-call</string>
          </dict>
        </array>
      </dict>
      <key>for-expression</key>
      <dict>
        <key>name</key>
        <string>meta.for-expression.bicep</string>
        <key>begin</key>
        <string>\[(?:\s|/\*.*\*/)*(\bfor\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#for-expression-in</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#for-expression-end</string>
          </dict>
        </array>
      </dict>
      <key>for-expression-end</key>
      <dict>
        <key>name</key>
        <string>meta.for-expression-end.bicep</string>
        <key>begin</key>
        <string>(?&lt;=:)(?:\s|/\*.*\*/)*</string>
        <key>end</key>
        <string>(?:\s|/\*.*\*/)*(?=])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>for-expression-in</key>
      <dict>
        <key>name</key>
        <string>meta.for-expression-in.bicep</string>
        <key>begin</key>
        <string>(?&lt;=\bfor\b)</string>
        <key>end</key>
        <string>:</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#for-expression-in-start</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#for-expression-in-end</string>
          </dict>
        </array>
      </dict>
      <key>for-expression-in-end</key>
      <dict>
        <key>name</key>
        <string>meta.for-expression-in-end.bicep</string>
        <key>begin</key>
        <string>(?&lt;=\bin\b)(?:\s|/\*.*\*/)*</string>
        <key>end</key>
        <string>(?=:)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>for-expression-in-start</key>
      <dict>
        <key>name</key>
        <string>meta.for-expression-in-start.bicep</string>
        <key>begin</key>
        <string>(?&lt;=\bfor\b)(?:\s|/\*.*\*/)*</string>
        <key>end</key>
        <string>(\bin\b)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>function-call</key>
      <dict>
        <key>name</key>
        <string>meta.function-call.bicep</string>
        <key>begin</key>
        <string>(\b[_$[:alpha:]][_$[:alnum:]]*\b)(?:\s|/\*.*\*/)*\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>name</key>
        <string>variable.other.readwrite.bicep</string>
        <key>match</key>
        <string>\b[_$[:alpha:]][_$[:alnum:]]*\b(?!(?:\s|/\*.*\*/)*\()</string>
      </dict>
      <key>if-expression</key>
      <dict>
        <key>name</key>
        <string>meta.if-expression.bicep</string>
        <key>begin</key>
        <string>(\bif\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#if-expression-start</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if-expression-end</string>
          </dict>
        </array>
      </dict>
      <key>if-expression-end</key>
      <dict>
        <key>name</key>
        <string>meta.if-expression-end.bicep</string>
        <key>begin</key>
        <string>(?&lt;=\))(?:\s|/\*.*\*/)*(?={)</string>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#object-literal</string>
          </dict>
        </array>
      </dict>
      <key>if-expression-start</key>
      <dict>
        <key>name</key>
        <string>meta.if-expression-start.bicep</string>
        <key>begin</key>
        <string>(?&lt;=\bif\b)(?:\s|/\*.*\*/)*\(</string>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>line-comment</key>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.bicep</string>
        <key>match</key>
        <string>//.*$</string>
      </dict>
      <key>module-statement</key>
      <dict>
        <key>name</key>
        <string>meta.module-statement.bicep</string>
        <key>begin</key>
        <string>(\bmodule\b)(?:\s|/\*.*\*/)*(\b[_$[:alpha:]][_$[:alnum:]]*\b)(?:\s|/\*.*\*/)*(?=')</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.name.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-statement-end</string>
          </dict>
        </array>
      </dict>
      <key>module-statement-end</key>
      <dict>
        <key>name</key>
        <string>meta.module-statement-end.bicep</string>
        <key>begin</key>
        <string>(?&lt;=')(?:\s|/\*.*\*/)*=(?:\s|/\*.*\*/)*</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>named-literal</key>
      <dict>
        <key>name</key>
        <string>constant.language.bicep</string>
        <key>match</key>
        <string>\b(true|false|null)\b</string>
      </dict>
      <key>numeric-literal</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.bicep</string>
        <key>match</key>
        <string>[0-9]+</string>
      </dict>
      <key>object-literal</key>
      <dict>
        <key>name</key>
        <string>meta.object-literal.bicep</string>
        <key>begin</key>
        <string>{</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#object-property</string>
          </dict>
        </array>
      </dict>
      <key>object-property</key>
      <dict>
        <key>name</key>
        <string>meta.object-property.bicep</string>
        <key>begin</key>
        <string>^(?!(?:\s|/\*.*\*/)*})</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#object-property-start</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object-property-end</string>
          </dict>
        </array>
      </dict>
      <key>object-property-end</key>
      <dict>
        <key>name</key>
        <string>meta.object-property-end.bicep</string>
        <key>begin</key>
        <string>(?&lt;=:)(?:\s|/\*.*\*/)*</string>
        <key>end</key>
        <string>(?:\s|/\*.*\*/)*$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>object-property-key-identifier</key>
      <dict>
        <key>name</key>
        <string>meta.object-property-key-identifier.bicep</string>
        <key>match</key>
        <string>(\b[_$[:alpha:]][_$[:alnum:]]*\b)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.bicep</string>
          </dict>
        </dict>
      </dict>
      <key>object-property-start</key>
      <dict>
        <key>name</key>
        <string>meta.object-property-start.bicep</string>
        <key>begin</key>
        <string>^(?:\s|/\*.*\*/)*</string>
        <key>end</key>
        <string>(?:\s|/\*.*\*/)*:</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object-property-key-identifier</string>
          </dict>
        </array>
      </dict>
      <key>output-statement</key>
      <dict>
        <key>name</key>
        <string>meta.output-statement.bicep</string>
        <key>begin</key>
        <string>(\boutput\b)(?:\s|/\*.*\*/)*(\b[_$[:alpha:]][_$[:alnum:]]*\b)(?:\s|/\*.*\*/)*(\b[_$[:alpha:]][_$[:alnum:]]*\b)(?:\s|/\*.*\*/)*=(?:\s|/\*.*\*/)*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.name.bicep</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.name.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>param-statement</key>
      <dict>
        <key>name</key>
        <string>meta.param-statement.bicep</string>
        <key>begin</key>
        <string>(\bparam\b)(?:\s|/\*.*\*/)*(\b[_$[:alpha:]][_$[:alnum:]]*\b)(?:\s|/\*.*\*/)*(\b[_$[:alpha:]][_$[:alnum:]]*\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.name.bicep</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.name.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>resource-statement</key>
      <dict>
        <key>name</key>
        <string>meta.resource-statement.bicep</string>
        <key>begin</key>
        <string>(\bresource\b)(?:\s|/\*.*\*/)*(\b[_$[:alpha:]][_$[:alnum:]]*\b)(?:\s|/\*.*\*/)*(?=')</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.name.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#resource-statement-end</string>
          </dict>
        </array>
      </dict>
      <key>resource-statement-end</key>
      <dict>
        <key>name</key>
        <string>meta.resource-statement-end.bicep</string>
        <key>begin</key>
        <string>(?&lt;=')(?:\s|/\*.*\*/)*=(?:\s|/\*.*\*/)*</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>statement</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#decorator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#targetscope-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#param-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#resource-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#var-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#output-statement</string>
          </dict>
        </array>
      </dict>
      <key>string-literal</key>
      <dict>
        <key>name</key>
        <string>string.quoted.single.bicep</string>
        <key>begin</key>
        <string>'(?!'')</string>
        <key>end</key>
        <string>'</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escape-character</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-literal-subst</string>
          </dict>
        </array>
      </dict>
      <key>string-literal-subst</key>
      <dict>
        <key>name</key>
        <string>meta.string-literal-subst.bicep</string>
        <key>begin</key>
        <string>(?&lt;!\\)(\${)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end.bicep</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>string-verbatim</key>
      <dict>
        <key>name</key>
        <string>string.quoted.multi.bicep</string>
        <key>begin</key>
        <string>'''</string>
        <key>end</key>
        <string>'''</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>targetscope-statement</key>
      <dict>
        <key>name</key>
        <string>meta.targetscope-statement.bicep</string>
        <key>begin</key>
        <string>(\btargetScope\b)(?:\s|/\*.*\*/)*=(?:\s|/\*.*\*/)*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>var-statement</key>
      <dict>
        <key>name</key>
        <string>meta.var-statement.bicep</string>
        <key>begin</key>
        <string>(\bvar\b)(?:\s|/\*.*\*/)*(\b[_$[:alpha:]][_$[:alnum:]]*\b)(?:\s|/\*.*\*/)*=(?:\s|/\*.*\*/)*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.declaration.bicep</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.name.bicep</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>