#################################################################################
#                           Onebranch Retail Pipeline                           #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

# https://aka.ms/obpipelines/triggers
trigger:
  batch: true
  branches:
    include:
      - main

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
  CI: true
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  system.debug: ${{ parameters.debug }}

  BuildSolution: $(Build.SourcesDirectory)/Bicep.sln
  BuildConfiguration: Release
  TargetFramework: net6.0

  # Docker images which are used to build the project https://aka.ms/obpipelines/containers
  WindowsContainerImage: 'cdpxwin1809.azurecr.io/global/vse2019:latest'
  LinuxContainerImage: 'cdpxlinux.azurecr.io/global/ubuntu-1604-all:4.0'
resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    git:
      fetchDepth: -1
      longpaths: true
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      # tsa:
      #  enabled: false # onebranch publish all sdl results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      cg:
        failOnAlert: false # disable build breaks due to CG alerts
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
      armory:
        break: false # the example templates are similar to the quickstart repo - azure compliance rules are not applicable here
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress
      #   suppressionSet: default

    stages:
    - template: Common.yml
      parameters:
        official: true
