&lt;Project&gt;
  &lt;PropertyGroup&gt;
    &lt;ManagePackageVersionsCentrally&gt;true&lt;/ManagePackageVersionsCentrally&gt;
    &lt;CentralPackageTransitivePinningEnabled&gt;true&lt;/CentralPackageTransitivePinningEnabled&gt;
  &lt;/PropertyGroup&gt;
  &lt;ItemGroup&gt;
    &lt;GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.10.91" PrivateAssets="All" /&gt;
    &lt;GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" PrivateAssets="All" /&gt;
    &lt;GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" /&gt;
    &lt;GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.13.2" PrivateAssets="All" /&gt;
  &lt;/ItemGroup&gt;
  &lt;ItemGroup&gt;
    &lt;PackageVersion Include="Azure.Bicep.Internal.RoslynAnalyzers" Version="0.1.60" /&gt;
    &lt;PackageVersion Include="Azure.Bicep.Types" Version="0.6.129" /&gt;
    &lt;PackageVersion Include="Azure.Bicep.Types.Az" Version="0.2.911" /&gt;
    &lt;PackageVersion Include="Azure.Bicep.Types.K8s" Version="0.1.644" /&gt;
    &lt;PackageVersion Include="Azure.Containers.ContainerRegistry" Version="1.3.0" /&gt;
    &lt;PackageVersion Include="Azure.Deployments.Engine" Version="1.683.0" /&gt;
    &lt;PackageVersion Include="Azure.Deployments.Extensibility.Core" Version="0.1.67" /&gt;
    &lt;PackageVersion Include="Azure.Deployments.Internal.GenerateNotice" Version="0.1.60" /&gt;
    &lt;PackageVersion Include="Azure.Deployments.Templates" Version="1.683.0" /&gt;
    &lt;PackageVersion Include="Azure.Identity" Version="1.21.0" /&gt;
    &lt;PackageVersion Include="Azure.ResourceManager.ResourceGraph" Version="1.1.1" /&gt;
    &lt;PackageVersion Include="Azure.ResourceManager.Resources" Version="1.11.2" /&gt;
    &lt;PackageVersion Include="BenchmarkDotNet" Version="0.15.8" /&gt;
    &lt;PackageVersion Include="CommandLineParser" Version="2.9.1" /&gt;
    &lt;PackageVersion Include="DiffPlex" Version="1.9.0" /&gt;
    &lt;!-- Version 8 or above are no longer fully open-source --&gt;
    &lt;PackageVersion Include="FluentAssertions" Version="7.2.0" /&gt;
    &lt;PackageVersion Include="Google.Protobuf" Version="3.35.1" /&gt;
    &lt;PackageVersion Include="Grpc.AspNetCore" Version="2.71.0" /&gt;
    &lt;PackageVersion Include="Grpc.AspNetCore.Server" Version="2.83.0" /&gt;
    &lt;PackageVersion Include="Grpc.AspNetCore.Server.Reflection" Version="2.80.0" /&gt;
    &lt;PackageVersion Include="Grpc.Core.Testing" Version="2.46.6" /&gt;
    &lt;PackageVersion Include="Grpc.Net.Client" Version="2.76.0" /&gt;
    &lt;PackageVersion Include="Grpc.Tools" Version="2.83.0" /&gt;
    &lt;PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" /&gt;
    &lt;PackageVersion Include="JsonDiffPatch.Net" Version="2.3.0" /&gt;
    &lt;PackageVersion Include="JsonPatch.Net" Version="3.3.0" /&gt;
    &lt;PackageVersion Include="JsonPath.Net" Version="2.1.1" /&gt;
    &lt;PackageVersion Include="JsonSchema.Net" Version="7.3.3" /&gt;
    &lt;PackageVersion Include="Microsoft.Playwright" Version="1.56.0" /&gt;
    &lt;PackageVersion Include="Microsoft.Playwright.Xunit" Version="1.56.0" /&gt;
    &lt;PackageVersion Include="MSTest" Version="4.3.3" /&gt;
    &lt;PackageVersion Include="Markdig" Version="1.3.2" /&gt;
    &lt;PackageVersion Include="MessagePack" Version="3.1.7" /&gt;
    &lt;PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Microsoft.Build.Framework" Version="18.8.2" /&gt;
    &lt;PackageVersion Include="Microsoft.Build.Utilities.Core" Version="18.8.2" /&gt;
    &lt;PackageVersion Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.11.0" /&gt;
    &lt;PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.7" /&gt;
    &lt;PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Microsoft.IO.Redist" Version="6.1.0" /&gt;
    &lt;PackageVersion Include="Microsoft.NET.Sdk.WebAssembly.Pack" Version="10.0.8" /&gt;
    &lt;PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" /&gt;
    &lt;PackageVersion Include="Microsoft.Net.Compilers.Toolset" Version="4.12.0" /&gt;
    &lt;PackageVersion Include="Microsoft.PowerPlatform.ResourceStack" Version="7.0.0.2080" /&gt;
    &lt;PackageVersion Include="Microsoft.Test.Apex.VisualStudio" Version="17.11.35222.181" /&gt;
    &lt;PackageVersion Include="Microsoft.VSSDK.BuildTools" Version="17.12.2069" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Composition" Version="17.12.18" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.CoreUtility" Version="17.12.215" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Editor" Version="17.12.215" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.LanguageServer.Client" Version="17.12.48" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.LanguageServer.Protocol" Version="17.2.8" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.SDK" Version="17.11.40262" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Setup.Configuration.Interop" Version="3.12.2149" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Shell.Framework" Version="17.12.40391" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Shell.Interop" Version="17.12.40391" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Threading" Version="17.12.19" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Utilities" Version="17.12.40391" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Workspace" Version="17.1.11-preview-0002" /&gt;
    &lt;PackageVersion Include="Microsoft.VisualStudio.Workspace.VSIntegration" Version="17.1.11-preview-0002" /&gt;
    &lt;PackageVersion Include="Microsoft.Visualstudio.Telemetry" Version="17.12.48" /&gt;
    &lt;PackageVersion Include="ModelContextProtocol" Version="2.0.0" /&gt;
    &lt;PackageVersion Include="ModelContextProtocol.AspNetCore" Version="1.2.0" /&gt;
    &lt;PackageVersion Include="Moq" Version="4.20.72" /&gt;
    &lt;PackageVersion Include="Msagl" Version="1.2.1" /&gt;
    &lt;PackageVersion Include="Newtonsoft.Json" Version="13.0.3" /&gt;
    &lt;PackageVersion Include="Newtonsoft.Json.Schema" Version="4.0.1" /&gt;
    &lt;PackageVersion Include="NuGet.CommandLine" Version="6.6.2" /&gt;
    &lt;PackageVersion Include="OmniSharp.Extensions.LanguageClient" Version="0.19.9" /&gt;
    &lt;PackageVersion Include="OmniSharp.Extensions.LanguageServer" Version="0.19.9" /&gt;
    &lt;PackageVersion Include="OrasProject.Oras" Version="0.7.0" /&gt;
    &lt;PackageVersion Include="PublicApiGenerator" Version="11.5.4" /&gt;
    &lt;PackageVersion Include="RichardSzalay.MockHttp" Version="7.0.0" /&gt;
    &lt;PackageVersion Include="Sarif.Sdk" Version="5.4.3" /&gt;
    &lt;PackageVersion Include="Scriban" Version="7.2.6" /&gt;
    &lt;PackageVersion Include="Semver" Version="3.0.0" /&gt;
    &lt;PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" /&gt;
    &lt;PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" /&gt;
    &lt;PackageVersion Include="Serilog.Sinks.TextWriter" Version="3.0.0" /&gt;
    &lt;PackageVersion Include="SharpYaml" Version="3.12.0" /&gt;
    &lt;PackageVersion Include="Spectre.Console" Version="0.57.0" /&gt;
    &lt;PackageVersion Include="Spectre.Console.Testing" Version="0.57.0" /&gt;
    &lt;PackageVersion Include="StreamJsonRpc" Version="2.20.20" /&gt;
    &lt;PackageVersion Include="System.CommandLine" Version="2.0.11" /&gt;
    &lt;PackageVersion Include="System.Collections.Immutable" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.1.1" /&gt;
    &lt;PackageVersion Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.1.1" /&gt;
    &lt;PackageVersion Include="System.Memory.Data" Version="10.0.9" /&gt;
    &lt;!-- force an upgrade of this dependency as it seems to cause build flakiness for unknown reasons --&gt;
    &lt;PackageVersion Include="System.Private.Uri" Version="4.3.2" /&gt;
    &lt;!-- pin to patched version to resolve CVE-2026-33116 (https://github.com/advisories/GHSA-37gx-xxp4-5rgx) --&gt;
    &lt;PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.11" /&gt;
    &lt;PackageVersion Include="System.Text.Json" Version="10.0.9" /&gt;
    &lt;PackageVersion Include="Tools.InnoSetup" Version="6.0.5" /&gt;
  &lt;/ItemGroup&gt;
&lt;/Project&gt;
