name: Experimental

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-bicep:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        include:
        - os: 'windows-latest'
          rid: 'win-x64'
          configuration: 'Release'
        - os: 'ubuntu-latest'
          rid: 'linux-x64'
          configuration: 'Release'
        - os: 'macos-latest'
          rid: 'osx-x64'
          configuration: 'Release'

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      
      - name: Build
        run: dotnet build --nologo --configuration ${{ matrix.configuration }}
      
      - name: Test
        run: dotnet test --nologo --configuration ${{ matrix.configuration }} --collect:"XPlat Code Coverage"
      
      - name: Publish Language Server
        run: dotnet publish --nologo --configuration ${{ matrix.configuration }} ./src/Bicep.LangServer/Bicep.LangServer.csproj
      
      - name: Publish Bicep
        run: dotnet publish --nologo --configuration ${{ matrix.configuration }} --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -r ${{ matrix.rid }} ./src/Bicep.Cli/Bicep.Cli.csproj
      
      - name: Upload Language Server
        uses: actions/upload-artifact@v2
        with:
          name: LangServer_${{ matrix.configuration }}_${{ matrix.rid }}
          path: ./src/Bicep.LangServer/bin/${{ matrix.configuration }}/netcoreapp3.1/publish/*
      
      - name: Upload Bicep
        uses: actions/upload-artifact@v2
        with:
          name: Bicep_${{ matrix.configuration }}_${{ matrix.rid }}
          path: ./src/Bicep.Cli/bin/${{ matrix.configuration }}/netcoreapp3.1/${{ matrix.rid }}/publish/*