name: Update Dependencies
# This action can be run on-demand against a branch.
# It attempts to update dotnet & npm dependencies, and commits and pushes changes if there are any.

on:
  workflow_dispatch:

jobs:
  main:
    name: Update Dependencies
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - name: Install Tools
        run: |
          npm install -g npm-check-updates
          dotnet tool install -g dotnet-outdated-tool

      - name: Update Dependencies
        continue-on-error: true
        run: ./scripts/update_dependencies.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-dependencies
          delete-branch: true
          title: |
            Update NPM & Dotnet Dependencies
          commit-message: |
            Update NPM & Dotnet Dependencies
          labels: dependencies
          draft: false
